# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup cross compiler
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Download dependence
      run: go mod tidy
      
    - name: Build
      env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 1
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          GOFLAGS: "-tags=linux,arm64"
      run: go build -v -ldflags "-linkmode external -extldflags '-static -s -w'" -o EasierConnect_arm64-linux-static

    - name: Test
      run: file EasierConnect_arm64-linux-static

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: EasierConnect-arm64-linux
        path: EasierConnect_arm64-linux-static
